# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1
executors:
  ruby24:
    docker:
      - image: "circleci/ruby:2.4-buster"
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-buster"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-buster"
  ruby27:
    docker:
      - image: "circleci/ruby:2.7-buster"
commands:
  run-ci:
    steps:
      - checkout
      - run:
          name: Bundle
          command: "gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: CI
          command: "bundle exec toys ci"
  run-test:
    steps:
      - checkout
      - run:
          name: Bundle
          command: "gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: Test
          command: "bundle exec toys test"
  run-release:
    steps:
      - checkout
      - run:
          name: Release
          command: "gem install --no-document toys && toys push-release"
jobs:
  test-ruby24:
    executor: ruby24
    steps:
      - run-test
  test-ruby25:
    executor: ruby25
    steps:
      - run-test
  test-ruby26:
    executor: ruby26
    steps:
      - run-test
  test-ruby27:
    executor: ruby27
    steps:
      - run-ci
  release:
    executor: ruby27
    steps:
      - run-release
workflows:
  version: 2
  builds:
    jobs:
      - test-ruby24:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
      - test-ruby25:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
      - test-ruby26:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
      - test-ruby27:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
      - release:
          requires:
            - test-ruby24
            - test-ruby25
            - test-ruby26
            - test-ruby27
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
