name: Ruby Lint CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    if: ${{ github.repository == 'GoogleCloudPlatform/functions-framework-ruby' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          index.rubygems.org:443
          objects.githubusercontent.com:443
          release-assets.githubusercontent.com:443
          rubygems.org:443

    - name: Checkout repo
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Install Ruby 3.1
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: "3.4.10"
        bundler-cache: true
    - name: Install toys
      run: gem install --no-document toys
    - name: Lint
      run: "toys ci --only --test-rubocop"
