name: "Push docs to gh-pages"

on:
  release:
    types: [published]

jobs:
  push-gh-pages:
    env:
      ruby_version: "3.0"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@4d060a10e6d98429c69057f0aafbc65fb982bae8 # v1.137.0
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Install toys
        run: gem install --no-document toys
      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release publish-gh-pages --verbose < /dev/null
