name: "Push docs to gh-pages"

on:
  release:
    types: [published]

# Declare default permissions as read only.
permissions: read-all

jobs:
  push-gh-pages:
    env:
      ruby_version: "3.0"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899 # v1.173.0
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Install toys
        run: gem install --no-document toys
      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release publish-gh-pages --verbose < /dev/null
